2023-05-22 00:53:25 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Read+timed+out.+%28read+timeout%3D10%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB52760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:30 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB620A0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB68790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:35 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB62190%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB625B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:40 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB62070%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB74790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:45 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB621C0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB7A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:50 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB624F0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB7F970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:55 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB622B0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBEDBB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:00 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB74760%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBF38E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:05 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB7A850%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBF5C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:10 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB7F880%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBFAD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:15 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABBEDD00%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC00BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:20 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABBF5C10%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBFECD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:25 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABBF5C10%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC0BDC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:58 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+%28%27Connection+aborted.%27%2C+ConnectionResetError%2810054%2C+%27An+existing+connection+was+forcibly+closed+by+the+remote+host%27%2C+None%2C+10054%2C+None%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC1D4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:56:15 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+%28%27Connection+aborted.%27%2C+ConnectionResetError%2810054%2C+%27An+existing+connection+was+forcibly+closed+by+the+remote+host%27%2C+None%2C+10054%2C+None%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC3AC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:21 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+%28%27Connection+aborted.%27%2C+ConnectionResetError%2810054%2C+%27An+existing+connection+was+forcibly+closed+by+the+remote+host%27%2C+None%2C+10054%2C+None%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A78A0D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:26 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FE700%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A811FC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:31 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FEDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A8118130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:36 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FEDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A9127280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:41 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FEDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A912C370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:46 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A811F820%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A9131190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:51 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A81189D0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A91362E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:56 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A8118EE0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A913A3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:19:30 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Ffapi%2Fv1%2FpremiumIndex%3Fsymbol%3DBTCUSDT+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A913A640%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A9149B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
