2023-05-22 00:53:25 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Read+timed+out.+%28read+timeout%3D10%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB52760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:30 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB620A0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB68790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:35 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB62190%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB625B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:40 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB62070%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB74790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:45 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB621C0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB7A880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:50 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB624F0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABB7F970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:53:55 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB622B0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBEDBB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:00 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB74760%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBF38E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:05 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB7A850%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBF5C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:10 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABB7F880%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBFAD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:15 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABBEDD00%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC00BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:20 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABBF5C10%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABBFECD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:25 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000158ABBF5C10%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC0BDC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:54:58 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+%28%27Connection+aborted.%27%2C+ConnectionResetError%2810054%2C+%27An+existing+connection+was+forcibly+closed+by+the+remote+host%27%2C+None%2C+10054%2C+None%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC1D4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 00:56:15 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+%28%27Connection+aborted.%27%2C+ConnectionResetError%2810054%2C+%27An+existing+connection+was+forcibly+closed+by+the+remote+host%27%2C+None%2C+10054%2C+None%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000158ABC3AC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:21 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+%28%27Connection+aborted.%27%2C+ConnectionResetError%2810054%2C+%27An+existing+connection+was+forcibly+closed+by+the+remote+host%27%2C+None%2C+10054%2C+None%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A78A0D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:26 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FE700%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A811FC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:31 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FEDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A8118130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:36 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FEDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A9127280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:41 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A80FEDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A912C370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:46 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A811F820%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A9131190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:51 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A81189D0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A91362E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:18:56 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A8118EE0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A913A3D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 15:19:30 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Ffapi%2Fv1%2FpremiumIndex%3Fsymbol%3DBTCUSDT+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x00000296A913A640%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+C%3A%5CUsers%5Cphamv%5CDownloads%5CBot%5CBot%5CBinance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000296A9149B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:02 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Read+timed+out.+%28read+timeout%3D10%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98A9352E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:07 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A935850%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98A93CA30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:12 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A935850%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E602580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:17 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A935970%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E60D370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:22 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A9359A0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E611130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:27 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A9359A0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E6141F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:32 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A9359A0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E61B0A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:37 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A928370%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E61BF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:42 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A928370%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E622B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:47 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E6113D0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E626A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:52 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E614FA0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E62A8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:21:57 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E614FA0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E62E790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:22:02 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E614FA0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E633640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:22:38 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Ffapi%2Fv1%2FpremiumIndex%3Fsymbol%3DBTCUSDT+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E6338B0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E641B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:23:43 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binancefuture.com%27%2C+port%3D443%29%3A+Read+timed+out.+%28read+timeout%3D10%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E6469D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:23:48 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E64C040%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E650220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:23:53 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E64C100%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E6530D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:23:58 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E64C190%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E653F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:03 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E64C130%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E659DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:08 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E64C130%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E65DCA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:13 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E6501F0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E65FB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:18 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E653E50%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E667A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:23 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E659DC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E66B8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:28 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E659DC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E672760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:33 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E65FB20%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E671610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:38 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E6679D0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E67B310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:43 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E66B0A0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E677310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:48 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E672730%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E681220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:53 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E6715E0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E6840D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:24:58 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A93CB50%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E684F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:25:03 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A93CB50%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E68CDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:25:08 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98A93CB50%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E690CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:25:13 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E681FD0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E695B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:25:18 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E684E50%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E698A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:25:23 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E68CDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E69E8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:25:28 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++run+%7C%7C%7C++last+error+HTTPSConnectionPool%28host%3D%27testnet.binance.vision%27%2C+port%3D443%29%3A+Max+retries+exceeded+with+url%3A+%2Fapi%2Fv3%2Fping+%28Caused+by+NewConnectionError%28%27%3Curllib3.connection.HTTPSConnection+object+at+0x000002A98E68CDC0%3E%3A+Failed+to+establish+a+new+connection%3A+%5BErrno+11001%5D+getaddrinfo+failed%27%29%29+%7C%7C%7C+Binance%5CBianceThread.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98E6A4AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
2023-05-22 17:26:05 || HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6136202579:AAFe3ZOnF7LgXHHX5r_QOBLXovsKOiHhbEo/sendMessage?chat_id=%40duongsau&text=L%E1%BB%97i++++%3Cmodule%3E+%7C%7C%7C++last+error+0+%7C%7C%7C+Main.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A98A3D4D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) || tele_notification 
